sonar.projectKey=ci-cd-project-by-jenkins-docker
sonar.projectName=CI-CD-Project-by-Jenkins-Docker
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.*,**/*.spec.*
sonar.exclusions=node_modules/**,dist/**
sonar.sourceEncoding=UTF-8
