// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-categories.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { menuCategories } from "npm:@/data/menuData";
var list_categories_default = defineTool({
  name: "list_categories",
  title: "List menu categories",
  description: "List all menu category names at Brundavanam Family Restaurant.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const categories = menuCategories.map((c) => c.label);
    return {
      content: [{ type: "text", text: categories.join("\n") }],
      structuredContent: { categories }
    };
  }
});

// src/lib/mcp/tools/list-menu.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
import { menuCategories as menuCategories2 } from "npm:@/data/menuData";
var list_menu_default = defineTool2({
  name: "list_menu",
  title: "List menu items",
  description: "List menu items with prices in INR. Optionally filter by a category label (case-insensitive, e.g. 'Veg Starters').",
  inputSchema: {
    category: z.string().trim().optional().describe("Optional category label to filter by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const filter = category?.toLowerCase();
    const cats = filter ? menuCategories2.filter((c) => c.label.toLowerCase() === filter) : menuCategories2;
    if (filter && cats.length === 0) {
      return {
        content: [{ type: "text", text: `No category matching "${category}".` }],
        isError: true
      };
    }
    const lines = [];
    const structured = cats.map((c) => {
      lines.push(`
## ${c.label}`);
      for (const it of c.items) lines.push(`- ${it.name} \u2014 \u20B9${it.price}`);
      return { category: c.label, items: c.items };
    });
    return {
      content: [{ type: "text", text: lines.join("\n").trim() }],
      structuredContent: { categories: structured }
    };
  }
});

// src/lib/mcp/tools/search-menu.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
import { menuCategories as menuCategories3 } from "npm:@/data/menuData";
var search_menu_default = defineTool3({
  name: "search_menu",
  title: "Search menu",
  description: "Search menu items by keyword in the dish name. Returns matches with price and category.",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Keyword to match against dish names."),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, limit }) => {
    const q = query.toLowerCase();
    const matches = [];
    for (const c of menuCategories3) {
      for (const it of c.items) {
        if (it.name.toLowerCase().includes(q)) {
          matches.push({ name: it.name, price: it.price, category: c.label });
          if (matches.length >= limit) break;
        }
      }
      if (matches.length >= limit) break;
    }
    const text = matches.length ? matches.map((m) => `- ${m.name} \u2014 \u20B9${m.price} (${m.category})`).join("\n") : `No dishes matching "${query}".`;
    return {
      content: [{ type: "text", text }],
      structuredContent: { matches }
    };
  }
});

// src/lib/mcp/tools/restaurant-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
var restaurant_info_default = defineTool4({
  name: "restaurant_info",
  title: "Restaurant info",
  description: "Get Brundavanam Family Restaurant contact details, address, and ordering links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Brundavanam Family Restaurant",
      type: "Family Restaurant (A/C)",
      address: "Nellore Road, Near Honda Showroom, Badvel, Kadapa District",
      phone: "+91 7075959303",
      whatsapp: "https://wa.me/917075959303",
      website: "https://yum-list-weaver.lovable.app"
    };
    const text = [
      info.name,
      info.type,
      `Address: ${info.address}`,
      `Phone: ${info.phone}`,
      `WhatsApp: ${info.whatsapp}`,
      `Website: ${info.website}`
    ].join("\n");
    return { content: [{ type: "text", text }], structuredContent: info };
  }
});

// src/lib/mcp/tools/order-link.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
import { menuCategories as menuCategories4 } from "npm:@/data/menuData";
var order_link_default = defineTool5({
  name: "build_whatsapp_order_link",
  title: "Build WhatsApp order link",
  description: "Build a prefilled WhatsApp link the customer can tap to place an order. Provide items by exact dish name and quantity.",
  inputSchema: {
    items: z3.array(
      z3.object({
        name: z3.string().trim().min(1),
        qty: z3.number().int().min(1).max(50)
      })
    ).min(1).describe("List of dishes with quantities."),
    customer_name: z3.string().trim().max(60).optional(),
    order_type: z3.enum(["dine-in", "takeaway"]).default("dine-in"),
    notes: z3.string().trim().max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ items, customer_name, order_type, notes }) => {
    const lookup = /* @__PURE__ */ new Map();
    for (const c of menuCategories4) for (const it of c.items) lookup.set(it.name.toLowerCase(), it.price);
    const resolved = [];
    const missing = [];
    for (const i of items) {
      const price = lookup.get(i.name.toLowerCase());
      if (price === void 0) missing.push(i.name);
      else resolved.push({ name: i.name, qty: i.qty, price });
    }
    if (missing.length) {
      return {
        content: [
          {
            type: "text",
            text: `Unknown dishes: ${missing.join(", ")}. Use search_menu to find exact names.`
          }
        ],
        isError: true
      };
    }
    const total = resolved.reduce((s, r) => s + r.price * r.qty, 0);
    const lines = [
      `Hi Brundavanam! I'd like to order:`,
      "",
      ...resolved.map((r) => `\u2022 ${r.name} x${r.qty} \u2014 \u20B9${r.price * r.qty}`),
      "",
      `Total: \u20B9${total}`,
      `Type: ${order_type === "dine-in" ? "Dine-in" : "Takeaway"}`
    ];
    if (customer_name) lines.push(`Name: ${customer_name}`);
    if (notes) lines.push(`Notes: ${notes}`);
    const message = lines.join("\n");
    const url = `https://wa.me/917075959303?text=${encodeURIComponent(message)}`;
    return {
      content: [{ type: "text", text: `${url}

---
${message}` }],
      structuredContent: { url, message, total, items: resolved, order_type }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "brundavanam-mcp",
  title: "Brundavanam Restaurant",
  version: "0.1.0",
  instructions: "Tools for Brundavanam Family Restaurant (Badvel, Kadapa). Browse the menu, search dishes by name, get contact/address info, and build a prefilled WhatsApp order link the customer can tap to place their order.",
  tools: [list_categories_default, list_menu_default, search_menu_default, restaurant_info_default, order_link_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
